Feature/milestone 1
oscardelalanza/book-store pull request #2
Opened 2020-07-20 21:38 UTC by oscardelalanza

2020-07-21 12:33 UTC, fatymahmed requested changes
## Hi @oscardelalanza, 
You have done a great job in this milestone 👏👏, just a few things to fix for this to be approved
  - Update your readme with relevant information [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)

**Please see my comment below for details**
## Status: Changes Required ♻️
_Feel free to reach out to me on slack (Fatima) if you have any questions or need any help_

2020-07-21 12:35 UTC, fatymahmed commented on package.json
> +    "react-scripts": "3.4.1",
- `prop-types` should be added to `package.json` see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/section/propTypes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896806/)

2020-07-21 12:40 UTC, fatymahmed commented on README.md
> +> has functional and technical requirements that you will need to implement.
- change this part to be about the project.

2020-07-21 20:49 UTC, oscardelalanza commented
### Changes
- Prop types added
- Readme updated

2020-07-22 05:57 UTC, Oghenebrume50 approved these changes
### APPROVED 

Hi @oscardelalanza good project setup, everything looks great here, you are ready to do great work on this repository :smile:  

**Please merge and move on, This is approved** :+1: 

**RAPHAEL NORIODE** :mask:  stay_safe

2020-07-23 23:09 UTC, merged