Feature/milestone 2
oscardelalanza/book-store pull request #4
Opened 2020-08-12 23:40 UTC by oscardelalanza

### What was made
- directories prepared
- App component implemented
- BookList component implemented
- Book component implemented
- Booksform component implemented
- Redux store, reducer and actions implemented

2020-08-13 18:13 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @oscardelalanza :hand: 
Nice job in this milestone so far :clap: 
But some changes are needed before moving on :muscle: 

- [x] I know your app has only one reducer right now, but let's not leave the reducer index file empty. We can make it ready to receive other reducers. Something like this:
```javascript
import { combineReducers } from 'redux'
import books from './books'

export default combineReducers({
  books,
})
```

Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-08-13 18:13 UTC, Torres-ssf commented on src/components/BooksList.jsx
> +});
- [ ] As it is requested in the instructions, we need to use the Presentational and Container Components approach. This means that components are divided based on their awareness of Redux. Container components are the ones that are aware of Redux existence and Presentation components are the ones that don't. Check the documentation [here](https://redux.js.org/basics/usage-with-react#presentational-and-container-components). Both BookList and BookForm (BookForm it's not connected to Redux yet but it's going to in a future milestone) should be placed in the `containers` directory.

2020-08-13 18:13 UTC, Torres-ssf commented on src/components/BooksForm.jsx
> +  </div>
- [ ] BookForm component should be placed in the `containers` directory

2020-08-14 02:03 UTC, oscardelalanza commented
### changes made
- `bookReducer` implemented in `combineReducers`
- `BooksList` and `BooksForm` moved to containers

2020-08-15 07:52 UTC, fatymahmed approved these changes
## Hi @oscardelalanza 
### Good job making the requested changes 🎉🎉
## Status: Approved ✔️

2020-08-15 21:33 UTC, merged